#!/usr/bin/env node
/**
 * generate-env.js
 *
 * Run this ONCE to generate a backend/.env file with strong secrets.
 * It will NOT overwrite an existing .env.
 *
 * Usage:
 *   cd "Smart Manufacturing ERP/backend"
 *   node generate-env.js
 *
 * Then edit .env and fill in MONGO_URI, SMTP_USER, SMTP_PASS.
 */

const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

const envPath = path.join(__dirname, '.env');

if (fs.existsSync(envPath)) {
  console.log('✅  backend/.env already exists — not overwriting.');
  console.log('   Delete it first if you want to regenerate secrets.');
  process.exit(0);
}

const secret64  = () => crypto.randomBytes(64).toString('hex');
const secret32  = () => crypto.randomBytes(32).toString('hex');

const content = `# ─── Smart Manufacturing ERP — Backend .env ────────────────────────────────
# Auto-generated by generate-env.js on ${new Date().toISOString()}
# NEVER commit this file to git.

# ─── Server ──────────────────────────────────────────────────────────────────
NODE_ENV=development
PORT=5000
API_VERSION=v1

# ─── MongoDB Atlas ★ REQUIRED ────────────────────────────────────────────────
# 1. Go to https://cloud.mongodb.com
# 2. Create a free M0 cluster
# 3. Database Access → Add user with readWrite role
# 4. Network Access → Add IP 0.0.0.0/0 (or your IP)
# 5. Connect → Drivers → copy the URI and paste below
MONGO_URI=mongodb+srv://REPLACE_USER:REPLACE_PASS@cluster0.xxxxx.mongodb.net/smart_mfg_erp?retryWrites=true&w=majority

# ─── JWT (auto-generated strong secrets) ─────────────────────────────────────
JWT_SECRET=${secret64()}
JWT_EXPIRES_IN=8h
JWT_REFRESH_SECRET=${secret64()}
JWT_REFRESH_EXPIRES_IN=30d

# ─── Bcrypt ───────────────────────────────────────────────────────────────────
BCRYPT_SALT_ROUNDS=12

# ─── CORS ─────────────────────────────────────────────────────────────────────
CORS_ORIGINS=http://localhost:5173,http://localhost:3000

# ─── Cookie ───────────────────────────────────────────────────────────────────
COOKIE_SECRET=${secret32()}
COOKIE_SECURE=false
COOKIE_SAME_SITE=lax

# ─── Rate Limiting ────────────────────────────────────────────────────────────
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=100
AUTH_RATE_LIMIT_MAX=10

# ─── Email / SMTP ─────────────────────────────────────────────────────────────
# Leave SMTP_USER empty → DEV EMAIL MODE (OTPs printed to terminal, no email sent)
#
# For Gmail:
#   SMTP_HOST=smtp.gmail.com
#   SMTP_PORT=587
#   SMTP_SECURE=false
#   SMTP_USER=your@gmail.com
#   SMTP_PASS=your-16-char-app-password  (myaccount.google.com/apppasswords)
#
# For Mailtrap (recommended testing):
#   Copy values from mailtrap.io inbox → SMTP Settings
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE=false
SMTP_USER=
SMTP_PASS=
EMAIL_FROM_NAME=Smart Manufacturing ERP
EMAIL_FROM_ADDRESS=noreply@smartmanufacturingerp.com

# ─── File Uploads ─────────────────────────────────────────────────────────────
UPLOAD_MAX_SIZE_MB=10
UPLOAD_ALLOWED_TYPES=image/jpeg,image/png,image/webp,application/pdf

# ─── Frontend URL (used in email links) ──────────────────────────────────────
FRONTEND_URL=http://localhost:5173

# ─── Logging ──────────────────────────────────────────────────────────────────
LOG_LEVEL=info
`;

fs.writeFileSync(envPath, content, 'utf8');

console.log('');
console.log('✅  backend/.env created with auto-generated secrets.');
console.log('');
console.log('⚠️  Required: edit backend/.env and set MONGO_URI');
console.log('   Format: mongodb+srv://USER:PASS@cluster.mongodb.net/smart_mfg_erp');
console.log('');
console.log('📬  Email: leave SMTP_USER empty for DEV EMAIL MODE');
console.log('   (OTPs and links will print to your terminal)');
console.log('');
console.log('🚀  Then run:  npm run dev');
console.log('');
